In [4]:
import pandas as pd
df = pd.DataFrame([["a", "x"],
                   ["a", "x"],
                   ["a", np.nan],
                   ["b", "y"]], dtype="category")

imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(df))

[['a' 'x']
 ['a' 'x']
 ['a' 'x']
 ['b' 'y']]


In [91]:
import tensorflow as tf
import keras

In [92]:
# Constant Trnsors
x = tf.constant([[5, 2], [1, 3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [93]:
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [94]:
print("Aqui o dtype", x.dtype)
print("Aqui o shape", x.shape)

Aqui o dtype <dtype: 'int32'>
Aqui o shape (2, 2)


In [95]:
ones = tf.ones(shape=(4,4))
zeros = tf.zeros(shape=(4,4))
print(ones)
print(zeros)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


In [96]:
random_floats = tf.random.normal(shape=(4,4), mean=0.0, stddev=1.0)
random_ints = tf.random.uniform(shape=(4,4), minval=0, maxval=10, dtype="int32")

print(random_floats)
print(random_ints)

tf.Tensor(
[[ 0.40754527 -0.98947674  0.02574982  0.7577073 ]
 [ 0.19375835  0.32681334 -0.41315946 -1.0953197 ]
 [-0.12834647  1.1091732  -0.6187683  -0.18008278]
 [ 0.00244933  0.6929563   1.2824197  -0.13641357]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[2 7 2 1]
 [8 7 6 2]
 [9 9 7 1]
 [5 5 1 9]], shape=(4, 4), dtype=int32)


In [97]:
# Variable tensors
initial_value = tf.random.normal(shape=(4,4))
a = tf.Variable(initial_value)
print(initial_value)
print(a)

tf.Tensor(
[[ 1.1551441   0.60057086 -0.10289282 -0.4653137 ]
 [ 0.8708803   1.2960113  -0.10215749  0.3286005 ]
 [ 0.10687343 -0.6880179  -0.91159374 -1.654839  ]
 [-0.19849642 -0.30487847  0.20681468 -0.36508146]], shape=(4, 4), dtype=float32)
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.1551441 ,  0.60057086, -0.10289282, -0.4653137 ],
       [ 0.8708803 ,  1.2960113 , -0.10215749,  0.3286005 ],
       [ 0.10687343, -0.6880179 , -0.91159374, -1.654839  ],
       [-0.19849642, -0.30487847,  0.20681468, -0.36508146]],
      dtype=float32)>


In [98]:
# Modifying the values of a variable tensor
new_value = tf.random.normal(shape=(4,4))
print("Before assign new values to 'a'")
print(a) 
a.assign(new_value)
print("\n\n\nAfter assign new values to 'a'")
print(a)
for i in range(4):
    for j in range(4):
        assert a[i,j] == new_value[i,j]
        
added_value = tf.random.normal(shape=(4,4))
a.assign_add(added_value)
for i in range(4):
    for j in range(4):
        assert a[i,j] == new_value[i,j] + added_value[i,j]
print("+")
print(added_value)
print("=")
print(a)

Before assign new values to 'a'
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.1551441 ,  0.60057086, -0.10289282, -0.4653137 ],
       [ 0.8708803 ,  1.2960113 , -0.10215749,  0.3286005 ],
       [ 0.10687343, -0.6880179 , -0.91159374, -1.654839  ],
       [-0.19849642, -0.30487847,  0.20681468, -0.36508146]],
      dtype=float32)>



After assign new values to 'a'
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.68362212e+00, -3.92901152e-01,  9.91967797e-01,
        -4.91323382e-01],
       [-1.09751113e-01,  1.11285925e-01,  1.55584253e-02,
         1.09220529e+00],
       [-1.11858058e+00, -8.80956352e-01,  4.98265140e-02,
         2.27205515e+00],
       [ 4.69782382e-01,  9.08876896e-01,  2.15615658e-03,
         1.57217789e+00]], dtype=float32)>
+
tf.Tensor(
[[ 1.6180454  -1.7764399   0.7954538   1.8387125 ]
 [ 2.0276284  -0.32959095  0.9455347   0.09089289]
 [-0.32055    -0.04092838  1.4108615   1.2921307 ]
 [-0.9135122  -1.58442

In [99]:
a = tf.random.uniform(shape=(4, 4), minval=1, maxval=3)
b = tf.random.uniform(shape=(4, 4), minval=1, maxval=3)

c = a + b
d = tf.square(c)
e = tf.exp(d)

In [100]:
print(a)
print("\n\n")
print(b)
print("\n\n")
print(c)
print("\n\n")
print(d)
print("\n\n")
print(e)
print("\n\n")

tf.Tensor(
[[1.2064722 2.0850587 1.0006375 2.6956894]
 [1.8493769 2.0728178 1.0529134 2.1878812]
 [2.4826326 1.6422379 1.5868051 1.6302793]
 [2.0928214 2.4972944 1.6231384 1.4282496]], shape=(4, 4), dtype=float32)



tf.Tensor(
[[2.8696568 2.3708205 2.2333405 1.4252715]
 [2.242848  1.6381156 2.1286764 1.0038776]
 [1.5761395 1.4440484 2.0620327 1.4767125]
 [1.3240621 2.8755388 2.8651388 2.1271987]], shape=(4, 4), dtype=float32)



tf.Tensor(
[[4.076129  4.455879  3.233978  4.120961 ]
 [4.092225  3.7109334 3.1815898 3.1917589]
 [4.058772  3.0862863 3.6488378 3.1069918]
 [3.4168835 5.3728333 4.4882774 3.5554483]], shape=(4, 4), dtype=float32)



tf.Tensor(
[[16.614828 19.85486  10.458614 16.98232 ]
 [16.746305 13.771027 10.122514 10.187325]
 [16.47363   9.525163 13.314017  9.653398]
 [11.675093 28.867336 20.144634 12.641212]], shape=(4, 4), dtype=float32)



tf.Tensor(
[[1.6433428e+07 4.1962010e+08 3.4843238e+04 2.3731666e+07]
 [1.8742522e+07 9.5649100e+05 2.4897277e+04 2.6564326e+04]
 [1

In [103]:
# Gradients

a = tf.random.normal(shape=(2, 2))
print(a)
b = tf.random.normal(shape=(2, 2))
print(b)
with tf.GradientTape() as tape:
    tape.watch(a)  # Start recording the history of operations applied to `a`
    c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
    print(c)
    # What's the gradient of `c` with respect to `a`?
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[-1.0527482   0.75779563]
 [-1.6400291   1.9951824 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.37962675 -1.3797079 ]
 [ 0.61301965  1.7622368 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.1191046 1.5741183]
 [1.7508537 2.6619976]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.9407058   0.48140958]
 [-0.9367025   0.7495057 ]], shape=(2, 2), dtype=float32)


In [104]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[-0.9407058   0.48140958]
 [-0.9367025   0.7495057 ]], shape=(2, 2), dtype=float32)


In [105]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a) + tf.square(b))
        dc_da = tape.gradient(c, a)
    d2c_da2 = outer_tape.gradient(dc_da, a)
    print(d2c_da2)

tf.Tensor(
[[0.10282564 0.48804766]
 [0.07001638 0.1646287 ]], shape=(2, 2), dtype=float32)


In [106]:
class Linear(keras.layers.Layer):
    """y = w.x + b"""

    def __init__(self, units=32):
        super().__init__()
        self.units = units

    def build(self, input_shape):
        self.w = self.add_weight(
            shape=(input_shape[-1], self.units),
            initializer="random_normal",
            trainable=True,
        )
        self.b = self.add_weight(
            shape=(self.units,), initializer="random_normal", trainable=True
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b


# Instantiate our layer.
linear_layer = Linear(4)

# This will also call `build(input_shape)` and create the weights.
y = linear_layer(tf.ones((2, 2)))

In [114]:
print(linear_layer.w)
print(linear_layer.b)

<tf.Variable 'linear/Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.00656738, -0.05906534, -0.01739354, -0.01835443],
       [ 0.06118776,  0.05847284, -0.02498482,  0.0067023 ]],
      dtype=float32)>
<tf.Variable 'linear/Variable:0' shape=(4,) dtype=float32, numpy=array([-0.02224028,  0.05659447, -0.00264184, -0.01528305], dtype=float32)>



In [115]:
# Prepare a dataset.
(x_train, y_train), _ = keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train.reshape(60000, 784).astype("float32") / 255, y_train)
)
dataset = dataset.shuffle(buffer_size=1024).batch(64)

# Instantiate our linear layer (defined above) with 10 units.
linear_layer = Linear(10)

# Instantiate a logistic loss function that expects integer targets.
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Instantiate an optimizer.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

# Iterate over the batches of the dataset.
for step, (x, y) in enumerate(dataset):
    # Open a GradientTape.
    with tf.GradientTape() as tape:
        # Forward pass.
        logits = linear_layer(x)

        # Loss value for this batch.
        loss = loss_fn(y, logits)

    # Get gradients of the loss wrt the weights.
    gradients = tape.gradient(loss, linear_layer.trainable_weights)

    # Update the weights of our linear layer.
    optimizer.apply_gradients(zip(gradients, linear_layer.trainable_weights))

    # Logging.
    if step % 100 == 0:
        print("Step:", step, "Loss:", float(loss))

11490434/11490434 [==============================] - 1s 0us/step
Step: 0 Loss: 2.280843496322632
Step: 100 Loss: 2.1765356063842773
Step: 200 Loss: 2.0470731258392334
Step: 300 Loss: 1.9574905633926392
Step: 400 Loss: 1.8988059759140015
Step: 500 Loss: 1.9319863319396973
Step: 600 Loss: 1.8085181713104248
Step: 700 Loss: 1.735289454460144
Step: 800 Loss: 1.6278748512268066
Step: 900 Loss: 1.5055415630340576


In [116]:
class ComputeSum(keras.layers.Layer):
    """Returns the sum of the inputs."""

    def __init__(self, input_dim):
        super().__init__()
        # Create a non-trainable weight.
        self.total = self.add_weight(
            initializer="zeros", shape=(input_dim,), trainable=False
        )

    def call(self, inputs):
        self.total.assign_add(tf.reduce_sum(inputs, axis=0))
        return self.total


my_sum = ComputeSum(2)
x = tf.ones((2, 2))

y = my_sum(x)
print(y.numpy())  # [2. 2.]

y = my_sum(x)
print(y.numpy())  # [4. 4.]

assert my_sum.weights == [my_sum.total]
assert my_sum.non_trainable_weights == [my_sum.total]
assert my_sum.trainable_weights == []

[2. 2.]
[4. 4.]


In [117]:
# Let's reuse the Linear class
# with a `build` method that we defined above.


class MLP(keras.layers.Layer):
    """Simple stack of Linear layers."""

    def __init__(self):
        super().__init__()
        self.linear_1 = Linear(32)
        self.linear_2 = Linear(32)
        self.linear_3 = Linear(10)

    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.linear_2(x)
        x = tf.nn.relu(x)
        return self.linear_3(x)


mlp = MLP()

# The first call to the `mlp` object will create the weights.
y = mlp(tf.ones(shape=(3, 64)))

# Weights are recursively tracked.
assert len(mlp.weights) == 6

In [118]:
mlp = keras.Sequential(
    [
        keras.layers.Dense(32, activation=tf.nn.relu),
        keras.layers.Dense(32, activation=tf.nn.relu),
        keras.layers.Dense(10),
    ]
)

In [119]:
class ActivityRegularization(keras.layers.Layer):
    """Layer that creates an activity sparsity regularization loss."""

    def __init__(self, rate=1e-2):
        super().__init__()
        self.rate = rate

    def call(self, inputs):
        # We use `add_loss` to create a regularization loss
        # that depends on the inputs.
        self.add_loss(self.rate * tf.reduce_sum(inputs))
        return inputs

In [120]:
# Let's use the loss layer in a MLP block.


class SparseMLP(keras.layers.Layer):
    """Stack of Linear layers with a sparsity regularization loss."""

    def __init__(self):
        super().__init__()
        self.linear_1 = Linear(32)
        self.regularization = ActivityRegularization(1e-2)
        self.linear_3 = Linear(10)

    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.regularization(x)
        return self.linear_3(x)


mlp = SparseMLP()
y = mlp(tf.ones((10, 10)))

print(mlp.losses)  # List containing one float32 scalar

[<tf.Tensor: shape=(), dtype=float32, numpy=0.13634712>]


In [121]:
# Losses correspond to the *last* forward pass.
mlp = SparseMLP()
mlp(tf.ones((10, 10)))
assert len(mlp.losses) == 1
mlp(tf.ones((10, 10)))
assert len(mlp.losses) == 1  # No accumulation.

# Let's demonstrate how to use these losses in a training loop.

# Prepare a dataset.
(x_train, y_train), _ = keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train.reshape(60000, 784).astype("float32") / 255, y_train)
)
dataset = dataset.shuffle(buffer_size=1024).batch(64)

# A new MLP.
mlp = SparseMLP()

# Loss and optimizer.
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

for step, (x, y) in enumerate(dataset):
    with tf.GradientTape() as tape:
        # Forward pass.
        logits = mlp(x)

        # External loss value for this batch.
        loss = loss_fn(y, logits)

        # Add the losses created during the forward pass.
        loss += sum(mlp.losses)

        # Get gradients of the loss wrt the weights.
        gradients = tape.gradient(loss, mlp.trainable_weights)

    # Update the weights of our linear layer.
    optimizer.apply_gradients(zip(gradients, mlp.trainable_weights))

    # Logging.
    if step % 100 == 0:
        print("Step:", step, "Loss:", float(loss))

Step: 0 Loss: 6.851256370544434
Step: 100 Loss: 2.5676000118255615
Step: 200 Loss: 2.410273551940918
Step: 300 Loss: 2.3714349269866943
Step: 400 Loss: 2.345013380050659
Step: 500 Loss: 2.330770254135132
Step: 600 Loss: 2.334320306777954
Step: 700 Loss: 2.322479724884033
Step: 800 Loss: 2.325767755508423
Step: 900 Loss: 2.3104195594787598


In [122]:
# Instantiate a metric object
accuracy = keras.metrics.SparseCategoricalAccuracy()

# Prepare our layer, loss, and optimizer.
model = keras.Sequential(
    [
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dense(10),
    ]
)
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = keras.optimizers.Adam(learning_rate=1e-3)

for epoch in range(2):
    # Iterate over the batches of a dataset.
    for step, (x, y) in enumerate(dataset):
        with tf.GradientTape() as tape:
            logits = model(x)
            # Compute the loss value for this batch.
            loss_value = loss_fn(y, logits)

        # Update the state of the `accuracy` metric.
        accuracy.update_state(y, logits)

        # Update the weights of the model to minimize the loss value.
        gradients = tape.gradient(loss_value, model.trainable_weights)
        optimizer.apply_gradients(zip(gradients, model.trainable_weights))

        # Logging the current accuracy value so far.
        if step % 200 == 0:
            print("Epoch:", epoch, "Step:", step)
            print("Total running accuracy so far: %.3f" % accuracy.result())

    # Reset the metric's state at the end of an epoch
    accuracy.reset_state()

Epoch: 0 Step: 0
Total running accuracy so far: 0.062
Epoch: 0 Step: 200
Total running accuracy so far: 0.740
Epoch: 0 Step: 400
Total running accuracy so far: 0.820
Epoch: 0 Step: 600
Total running accuracy so far: 0.853
Epoch: 0 Step: 800
Total running accuracy so far: 0.871
Epoch: 1 Step: 0
Total running accuracy so far: 0.969
Epoch: 1 Step: 200
Total running accuracy so far: 0.942
Epoch: 1 Step: 400
Total running accuracy so far: 0.941
Epoch: 1 Step: 600
Total running accuracy so far: 0.942
Epoch: 1 Step: 800
Total running accuracy so far: 0.942


In [123]:
class F1Score(keras.metrics.Metric):
    def __init__(self, name="f1_score", dtype="float32", threshold=0.5, **kwargs):
        super().__init__(name=name, dtype=dtype, **kwargs)
        self.threshold = 0.5
        self.true_positives = self.add_weight(
            name="tp", dtype=dtype, initializer="zeros"
        )
        self.false_positives = self.add_weight(
            name="fp", dtype=dtype, initializer="zeros"
        )
        self.false_negatives = self.add_weight(
            name="fn", dtype=dtype, initializer="zeros"
        )

    def update_state(self, y_true, y_pred, sample_weight=None):
        y_pred = tf.math.greater_equal(y_pred, self.threshold)
        y_true = tf.cast(y_true, tf.bool)
        y_pred = tf.cast(y_pred, tf.bool)

        true_positives = tf.cast(y_true & y_pred, self.dtype)
        false_positives = tf.cast(~y_true & y_pred, self.dtype)
        false_negatives = tf.cast(y_true & ~y_pred, self.dtype)

        if sample_weight is not None:
            sample_weight = tf.cast(sample_weight, self.dtype)
            true_positives *= sample_weight
            false_positives *= sample_weight
            false_negatives *= sample_weight

        self.true_positives.assign_add(tf.reduce_sum(true_positives))
        self.false_positives.assign_add(tf.reduce_sum(false_positives))
        self.false_negatives.assign_add(tf.reduce_sum(false_negatives))

    def result(self):
        precision = self.true_positives / (self.true_positives + self.false_positives)
        recall = self.true_positives / (self.true_positives + self.false_negatives)
        return precision * recall * 2.0 / (precision + recall)

    def reset_state(self):
        self.true_positives.assign(0)
        self.false_positives.assign(0)
        self.false_negatives.assign(0)

In [124]:
m = F1Score()
m.update_state([0, 1, 0, 0], [0.3, 0.5, 0.8, 0.9])
print("Intermediate result:", float(m.result()))

m.update_state([1, 1, 1, 1], [0.1, 0.7, 0.6, 0.0])
print("Final result:", float(m.result()))

Intermediate result: 0.5
Final result: 0.6000000238418579


In [125]:
# Prepare our layer, loss, and optimizer.
model = keras.Sequential(
    [
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dense(10),
    ]
)
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = keras.optimizers.Adam(learning_rate=1e-3)

# Create a training step function.


@tf.function  # Make it fast.
def train_on_batch(x, y):
    with tf.GradientTape() as tape:
        logits = model(x)
        loss = loss_fn(y, logits)
        gradients = tape.gradient(loss, model.trainable_weights)
    optimizer.apply_gradients(zip(gradients, model.trainable_weights))
    return loss


# Prepare a dataset.
(x_train, y_train), _ = keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train.reshape(60000, 784).astype("float32") / 255, y_train)
)
dataset = dataset.shuffle(buffer_size=1024).batch(64)

for step, (x, y) in enumerate(dataset):
    loss = train_on_batch(x, y)
    if step % 100 == 0:
        print("Step:", step, "Loss:", float(loss))

Step: 0 Loss: 2.284780740737915
Step: 100 Loss: 0.46894195675849915
Step: 200 Loss: 0.4187391400337219
Step: 300 Loss: 0.27640199661254883
Step: 400 Loss: 0.3544742465019226
Step: 500 Loss: 0.503422737121582
Step: 600 Loss: 0.3379875719547272
Step: 700 Loss: 0.3025365173816681
Step: 800 Loss: 0.2821683883666992
Step: 900 Loss: 0.07792575657367706
